### ISSUE TITLE
Missing or renamed "mountains.glb" file

### ISSUE THREAD

**Issue by Red1C3** [sarah-akk/Boat_Simulation#1]
When I try to run the app, it returns the following error
`[plugin:vite:import-analysis] Failed to resolve import "../static/Models/mountains.glb" from "src/main.js". Does the file exist?`

I got around it by copying moutains2.glb into mountains.glb and it worked out, though I'm not sure if its the wanted file or the actual file is missing from the assets.

**Comment by sarah-akk** [comment]
Thank you for bringing this up! Yes, the file mountains.glb was indeed missing from the assets, and copying mountains2.glb into mountains.glb was the correct workaround. I'll make sure the necessary files are updated in the assets to avoid this issue. Thanks again for your attention

**Comment by Red1C3** [comment]
Don't forget to close the issue after you update the repo!
